#!/data/data/com.termux/files/usr/bin/bash

clear

kill_color=$'\e[0m'

command -v youtube-dl &>/dev/null || printf "\e[031m Please install Youtube-dl or run install.sh\n$kill_color"

#[[ -f ~/bin ]] || printf "\e[031mRun the install.sh script.\n$kill_color"

echo "

████████╗███████╗██████╗ ███╗   ███╗██╗   ██╗██╗  ██╗

╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║   ██║╚██╗██╔╝

   ██║   █████╗  ██████╔╝██╔████╔██║██║   ██║ ╚███╔╝

   ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║   ██║ ██╔██╗

   ██║   ███████╗██║  ██║██║ ╚═╝ ██║╚██████╔╝██╔╝╚██╗

   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝

 ██╗  ██╗██╗   ██╗███╗  ██╗████████╗███████╗██████╗

 ██║  ██║██║   ██║████╗ ██║╚══██╔══╝██╔════╝██╔══██╗

 ███████║██║   ██║██╔██╗██║   ██║   █████╗  ██████╔╝

 ██╔══██║██║   ██║██║╚████║   ██║   ██╔══╝  ██╔══██╗

 ██║  ██║╚██████╔╝██║ ╚███║   ██║   ███████╗██║  ██║

 ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚══╝   ╚═╝   ╚══════╝╚═╝  ╚═╝

                  TERMUX HUNTER BD

              Download YouTube Video

              Download File YDownload"|lolcat                                                                      

echo -e "\e[032m________________________________

echo -e "\e[032m| Coder---> R.U.R. HaXoR.       |"|pv -qL 15

echo -e "\e[032m| Github: github.com/noobboss1  |"|pv -qL 15

echo -e "\e[032m| FB: m.me/R.U.R.HaXoR6939      |"|pv -qL 15

echo -e "\e[032m| FB: m.me/Noob.Boss.THBD       |"|pv -qL 15

echo -e "\e[032m|_______________________________|"|pv -qL 15

echo -e "\e[036m"

echo -e "\e[034mSelect Song Quality"|pv -qL 15

echo -e "\e[032m{1}~~~> 𝑴𝒖𝒔𝒊𝒄 𝑴𝒑3"|pv -qL 15

echo -e "\e[032m{2}~~~> 𝑽𝒊𝒅𝒆𝒐 360𝒑"|pv -qL 15

echo -e "\e[032m{3}~~~> 𝑽𝒊𝒅𝒆𝒐 480𝒑"|pv -qL 15

echo -e "\e[032m{4}~~~> 𝑽𝒊𝒅𝒆𝒐 720𝒑"|pv -qL 15

echo -e "\e[032m{5}~~~> 𝑽𝒊𝒅𝒆𝒐 1080𝒑"|pv -qL 15

echo -e "\e[032m{6}~~~> 𝑽𝒊𝒅𝒆𝒐 2160𝒑"|pv -qL 15

echo -e "\e[032m{𝑬}~~~> 𝑬𝒙𝒊𝒕"|pv -qL 15

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/YTDownloads/%(title)s.%(ext)s -f'

printf "\e[032m>>Choice Video Quality~~~> $kill_color"

read option

if [[ -z $option ]];

then

	clear	printf "\e[031mPlease choose a option!\n$kill_color"

else

case $option in

	1)

	echo "$command 140" > ~/.config/youtube-dl/config #option 1

	youtube-dl $1

	;;

	2)

	echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config #option 2

	youtube-dl $1

	;;

	3)

	echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config #option 3

	youtube-dl $1

	;;

	4)

	echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config #option 4

	youtube-dl $1

	;;

	5)

	echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config #option 5

	youtube-dl $1

	;;

	6)

	echo "$command \"best[height<=2160]\"" > ~/.config/youtube-dl/config

    	youtube-dl $1

	;;

	7)

	break

	;;

esac 

fi
